# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a94203a43adffe679160607cfce21ae30643947bb456ac31dc1cd530f650524e30683952d8a9e9ee3252fc5248af6c521f3effe7e326d34ad35393e013e22ac8

test:
  secret_key_base: 67fc003cbd7e3e763212ee7ead880a89aca65f9398dc313c5929ef7e08ae286ff7342cd42d4b88fd49f708a3726fea2a3650fbca7a699fcf01fb8dabfd5a4d58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
